/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/.well-known/jwks.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Jwks
         * @description Public verification keys, so other services can validate access tokens without secrets.
         */
        get: operations["jwks__well_known_jwks_json_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_v1_users_get"];
        put?: never;
        /** Create User */
        post: operations["create_user_api_v1_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User */
        get: operations["get_user_api_v1_users__user_id__get"];
        put?: never;
        post?: never;
        /**
         * Deactivate User
         * @description Soft delete: accounts are deactivated, never destroyed (docs/05 §8).
         */
        delete: operations["deactivate_user_api_v1_users__user_id__delete"];
        options?: never;
        head?: never;
        /** Update User */
        patch: operations["update_user_api_v1_users__user_id__patch"];
        trace?: never;
    };
    "/api/v1/users/{user_id}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set User Roles */
        put: operations["set_user_roles_api_v1_users__user_id__roles_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Roles */
        get: operations["list_roles_api_v1_roles_get"];
        put?: never;
        /** Create Role */
        post: operations["create_role_api_v1_roles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles/{role_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Role */
        patch: operations["update_role_api_v1_roles__role_id__patch"];
        trace?: never;
    };
    "/api/v1/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Permissions */
        get: operations["list_permissions_api_v1_permissions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingest/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit telemetry */
        post: operations["ingest_events_api_v1_ingest_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingest/parsers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Supported source parsers */
        get: operations["list_parsers_api_v1_ingest_parsers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingest/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List ingest sources */
        get: operations["list_sources_api_v1_ingest_sources_get"];
        put?: never;
        /** Register an ingest source */
        post: operations["create_source_api_v1_ingest_sources_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingest/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inspect an ingest source */
        get: operations["get_source_api_v1_ingest_sources__source_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Enable or disable an ingest source */
        patch: operations["update_source_api_v1_ingest_sources__source_id__patch"];
        trace?: never;
    };
    "/api/v1/ingest/sources/{source_id}/rotate-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue a new ingest token */
        post: operations["rotate_source_token_api_v1_ingest_sources__source_id__rotate_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search normalised events */
        post: operations["search_events_api_v1_events_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch one event */
        get: operations["get_event_api_v1_events__event_uid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List findings, newest first */
        get: operations["list_findings_api_v1_findings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/findings/{finding_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch one finding with its evidence event ids */
        get: operations["get_finding_api_v1_findings__finding_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/detection/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the loaded detection rules */
        get: operations["list_rules_api_v1_detection_rules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/detection/rules/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inspect one detection rule */
        get: operations["get_rule_api_v1_detection_rules__rule_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List incidents, most recent activity first */
        get: operations["list_incidents_api_v1_incidents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch an incident with its links, entities and assessment */
        get: operations["get_incident_api_v1_incidents__incident_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change the status of an incident (audited) */
        patch: operations["change_incident_status_api_v1_incidents__incident_id__patch"];
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The attack timeline: evidence events in order, grouped into steps */
        get: operations["get_timeline_api_v1_incidents__incident_id__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The entity graph: every edge cites the events that state it */
        get: operations["get_graph_api_v1_incidents__incident_id__graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Digests of the evidence events and the links that cite them */
        get: operations["get_evidence_api_v1_incidents__incident_id__evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Analyst notes, oldest first */
        get: operations["list_notes_api_v1_incidents__incident_id__notes_get"];
        put?: never;
        /** Add an analyst note (audited) */
        post: operations["add_note_api_v1_incidents__incident_id__notes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intel/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The configured threat-intelligence providers (may be none) */
        get: operations["list_providers_api_v1_intel_providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intel/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cached intel for indicators. Never calls a provider: enrichment runs in the background */
        post: operations["lookup_api_v1_intel_lookup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Config */
        get: operations["config_api_v1_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Audit */
        get: operations["list_audit_api_v1_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verify Audit */
        get: operations["verify_audit_api_v1_audit_verify_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuditEntryRead */
        AuditEntryRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Chain Index */
            chain_index: number;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Actor Id */
            actor_id: string | null;
            /** Actor Type */
            actor_type: string;
            /** Action */
            action: string;
            /** Resource Type */
            resource_type: string;
            /** Resource Id */
            resource_id: string | null;
            /** Before */
            before: {
                [key: string]: unknown;
            } | null;
            /** After */
            after: {
                [key: string]: unknown;
            } | null;
            /** Context */
            context: {
                [key: string]: unknown;
            } | null;
            /** Correlation Id */
            correlation_id: string | null;
            /**
             * Entry Hash
             * @description SHA-256 link in the tamper-evident chain
             */
            entry_hash: string;
        };
        /** AuditVerificationRead */
        AuditVerificationRead: {
            /** Valid */
            valid: boolean;
            /** Entries Checked */
            entries_checked: number;
            /** Head Hash */
            head_hash: string | null;
            /** Broken At Index */
            broken_at_index: number | null;
            /** Reason */
            reason: string | null;
        };
        /** EventPageResponse */
        EventPageResponse: {
            /** Items */
            items: {
                [key: string]: unknown;
            }[];
            /** Total */
            total: number;
            /** Total Is Lower Bound */
            total_is_lower_bound: boolean;
            /** Took Ms */
            took_ms: number;
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** EventSearchRequest */
        EventSearchRequest: {
            /**
             * Time From
             * Format: date-time
             */
            time_from: string;
            /**
             * Time To
             * Format: date-time
             */
            time_to: string;
            /** Class Uids */
            class_uids?: number[];
            /** Severity Min */
            severity_min?: number | null;
            /** Status Id */
            status_id?: number | null;
            /** Text */
            text?: string | null;
            /** Ip */
            ip?: string | null;
            /** User Name */
            user_name?: string | null;
            /** Hostname */
            hostname?: string | null;
            /** Source Id */
            source_id?: string | null;
            /**
             * Limit
             * @default 50
             */
            limit: number;
            /** Cursor */
            cursor?: string | null;
        };
        /** EvidenceEventRead */
        EvidenceEventRead: {
            /** Event Uid */
            event_uid: string;
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /** Class Uid */
            class_uid: number;
            /** Activity Id */
            activity_id: number | null;
            /** Status Id */
            status_id: number | null;
            /** Action */
            action: string;
            /** Outcome */
            outcome: string | null;
            /** Message */
            message: string | null;
            /**
             * Raw
             * @description Excerpt of the original record (at most 2,048 characters); null without event:read
             */
            raw: string | null;
            /** Roles */
            roles: {
                [key: string]: string[];
            };
            /** Detail */
            detail: {
                [key: string]: unknown;
            };
            /**
             * Cited By
             * @description Links that cite this event
             */
            cited_by: string[];
        };
        /** EvidenceResponse */
        EvidenceResponse: {
            /** Events */
            events: components["schemas"]["EvidenceEventRead"][];
            /** Unresolved Events */
            unresolved_events: string[];
        };
        /** FindingPageResponse */
        FindingPageResponse: {
            /** Items */
            items: components["schemas"]["FindingRead"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** FindingRead */
        FindingRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Rule Id */
            rule_id: string;
            /** Rule Title */
            rule_title: string;
            /** Rule Type */
            rule_type: string;
            /** Rule Version */
            rule_version: string;
            /** Severity Id */
            severity_id: number;
            /** Severity */
            severity: string;
            /** Techniques */
            techniques: string[];
            /** Tactics */
            tactics: string[];
            /** Entities */
            entities: {
                [key: string]: string[];
            };
            /** Evidence */
            evidence: string[];
            /** Evidence Count */
            evidence_count: number;
            /**
             * First Seen
             * Format: date-time
             */
            first_seen: string;
            /**
             * Last Seen
             * Format: date-time
             */
            last_seen: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** GraphEdgeRead */
        GraphEdgeRead: {
            /** Id */
            id: string;
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Relation */
            relation: string;
            /** Label */
            label: string;
            /**
             * First Seen
             * Format: date-time
             */
            first_seen: string;
            /**
             * Last Seen
             * Format: date-time
             */
            last_seen: string;
            /** Event Count */
            event_count: number;
            /**
             * Events
             * @description event_uids stating this relationship (at most 20)
             */
            events: string[];
            /** Detail */
            detail: {
                [key: string]: unknown;
            };
        };
        /** GraphNodeRead */
        GraphNodeRead: {
            /** Key */
            key: string;
            /** Type */
            type: string;
            /** Value */
            value: string;
            /** External */
            external: boolean;
            /**
             * First Seen
             * Format: date-time
             */
            first_seen: string;
            /**
             * Last Seen
             * Format: date-time
             */
            last_seen: string;
            /** Event Count */
            event_count: number;
            /**
             * Events
             * @description event_uids it appears in (at most 20)
             */
            events: string[];
        };
        /** GraphResponse */
        GraphResponse: {
            /** Nodes */
            nodes: components["schemas"]["GraphNodeRead"][];
            /** Edges */
            edges: components["schemas"]["GraphEdgeRead"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthReport */
        HealthReport: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Checks */
            checks: {
                [key: string]: "ok" | "failing" | "not_configured";
            };
            /** Version */
            version: string;
            /** Environment */
            environment: string;
        };
        /** IncidentDetailRead */
        IncidentDetailRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Severity Id */
            severity_id: number;
            /** Severity */
            severity: string;
            status: components["schemas"]["IncidentStatus"];
            resolution: components["schemas"]["Resolution"] | null;
            /** Techniques */
            techniques: string[];
            /** Tactics */
            tactics: string[];
            /** Finding Count */
            finding_count: number;
            /** Event Count */
            event_count: number;
            /**
             * First Seen
             * Format: date-time
             */
            first_seen: string;
            /**
             * Last Seen
             * Format: date-time
             */
            last_seen: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Closed At */
            closed_at: string | null;
            /**
             * Version
             * @description Send back when changing the status; a stale version is a 409
             */
            version: number;
            /** Assessment */
            assessment: {
                [key: string]: unknown;
            }[];
            /** Links */
            links: components["schemas"]["IncidentLinkRead"][];
            /** Entities */
            entities: components["schemas"]["IncidentEntityRead"][];
        };
        /** IncidentEntityRead */
        IncidentEntityRead: {
            /** Key */
            key: string;
            /** Type */
            type: string;
            /** Value */
            value: string;
            /**
             * Links
             * @description Whether this entity can join findings into the incident
             */
            links: boolean;
            /**
             * First Seen
             * Format: date-time
             */
            first_seen: string;
            /**
             * Last Seen
             * Format: date-time
             */
            last_seen: string;
            /**
             * Events
             * @description event_uids it was seen in (at most 20)
             */
            events: string[];
        };
        /** IncidentLinkRead */
        IncidentLinkRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Kind
             * @description `finding` or `event`
             */
            kind: string;
            /**
             * Rule
             * @description The correlation rule that created the link
             */
            rule: string;
            /** Reason */
            reason: string;
            /** Finding Id */
            finding_id: string | null;
            /** Event Uid */
            event_uid: string | null;
            /**
             * Evidence
             * @description event_uids this link brings into the incident
             */
            evidence: string[];
            /** Matched */
            matched: components["schemas"]["MatchedEntityRead"][];
            /** Detail */
            detail: {
                [key: string]: unknown;
            };
            /**
             * First Seen
             * Format: date-time
             */
            first_seen: string;
            /**
             * Last Seen
             * Format: date-time
             */
            last_seen: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** IncidentPageResponse */
        IncidentPageResponse: {
            /** Items */
            items: components["schemas"]["IncidentRead"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** IncidentRead */
        IncidentRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Severity Id */
            severity_id: number;
            /** Severity */
            severity: string;
            status: components["schemas"]["IncidentStatus"];
            resolution: components["schemas"]["Resolution"] | null;
            /** Techniques */
            techniques: string[];
            /** Tactics */
            tactics: string[];
            /** Finding Count */
            finding_count: number;
            /** Event Count */
            event_count: number;
            /**
             * First Seen
             * Format: date-time
             */
            first_seen: string;
            /**
             * Last Seen
             * Format: date-time
             */
            last_seen: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Closed At */
            closed_at: string | null;
            /**
             * Version
             * @description Send back when changing the status; a stale version is a 409
             */
            version: number;
        };
        /**
         * IncidentStatus
         * @enum {string}
         */
        IncidentStatus: "new" | "investigating" | "closed";
        /** IncidentStatusChange */
        IncidentStatusChange: {
            status: components["schemas"]["IncidentStatus"];
            resolution?: components["schemas"]["Resolution"] | null;
            /**
             * Version
             * @description The version you last read
             */
            version: number;
        };
        /** IngestErrorRead */
        IngestErrorRead: {
            /** Index */
            index: number;
            /** Reason */
            reason: string;
        };
        /** IngestResponse */
        IngestResponse: {
            /** Accepted */
            accepted: number;
            /** Rejected */
            rejected: number;
            /** Errors */
            errors: components["schemas"]["IngestErrorRead"][];
        };
        /** IntelLookup */
        IntelLookup: {
            /**
             * Indicators
             * @description `ip:…`, `domain:…` or `hash:…` keys
             */
            indicators: string[];
        };
        /** IntelLookupResponse */
        IntelLookupResponse: {
            /** Results */
            results: components["schemas"]["IntelResultRead"][];
            /**
             * Skipped
             * @description Keys that aren't indicators Sentinel-X looks up (e.g. internal IPs)
             */
            skipped: string[];
        };
        /** IntelResultRead */
        IntelResultRead: {
            /**
             * Indicator
             * @description `type:value`, matching incident entity keys
             */
            indicator: string;
            /** Provider */
            provider: string;
            /**
             * Status
             * @description `found`, `not_found` (asked, nothing known) or `error` (couldn't ask)
             */
            status: string;
            /**
             * Verdict
             * @description The provider's own classification; Sentinel-X does not merge providers
             */
            verdict: string;
            /** Confidence */
            confidence: number | null;
            /** Summary */
            summary: string;
            /** Tags */
            tags: string[];
            /** Related */
            related: components["schemas"]["RelatedRead"][];
            /** References */
            references: string[];
            /** Provider First Seen */
            provider_first_seen: string | null;
            /** Provider Last Seen */
            provider_last_seen: string | null;
            /**
             * Retrieved At
             * Format: date-time
             * @description When the provider was asked
             */
            retrieved_at: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Error */
            error: string | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /**
             * Password
             * Format: password
             */
            password: string;
        };
        /** MatchedEntityRead */
        MatchedEntityRead: {
            /**
             * Key
             * @description `type:value`, e.g. `ip:203.0.113.45`
             */
            key: string;
            /**
             * Incident Events
             * @description event_uids already in the incident that show this entity
             */
            incident_events: string[];
            /**
             * New Events
             * @description event_uids of the linked item that show this entity
             */
            new_events: string[];
        };
        /** MeResponse */
        MeResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Org Id
             * Format: uuid
             */
            org_id: string;
            /** Email */
            email: string;
            /** Full Name */
            full_name: string;
            /** Roles */
            roles: string[];
            /** Permissions */
            permissions: string[];
            /** Last Login At */
            last_login_at: string | null;
        };
        /** NoteCreate */
        NoteCreate: {
            /** Body */
            body: string;
        };
        /** NoteRead */
        NoteRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Author Id
             * Format: uuid
             */
            author_id: string;
            /** Author Email */
            author_email: string;
            /** Body */
            body: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** Page[AuditEntryRead] */
        Page_AuditEntryRead_: {
            /** Items */
            items: components["schemas"]["AuditEntryRead"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Page[UserRead] */
        Page_UserRead_: {
            /** Items */
            items: components["schemas"]["UserRead"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** ParserRead */
        ParserRead: {
            /** Name */
            name: string;
            /** Description */
            description: string;
        };
        /** PermissionRead */
        PermissionRead: {
            /** Name */
            name: string;
            /** Description */
            description: string;
        };
        /**
         * PlatformConfig
         * @description Non-secret runtime configuration only.
         */
        PlatformConfig: {
            /** Version */
            version: string;
            /** Environment */
            environment: string;
            /** Access Token Ttl Seconds */
            access_token_ttl_seconds: number;
            /** Refresh Token Ttl Seconds */
            refresh_token_ttl_seconds: number;
            /** Login Rate Limit */
            login_rate_limit: number;
            /** Login Rate Window Seconds */
            login_rate_window_seconds: number;
            /** Redis Configured */
            redis_configured: boolean;
            /** Metrics Enabled */
            metrics_enabled: boolean;
            /** Tracing Enabled */
            tracing_enabled: boolean;
            /** Jwt Signing Kid */
            jwt_signing_kid: string;
        };
        /** ProviderRead */
        ProviderRead: {
            /** Name */
            name: string;
            /** Title */
            title: string;
            /**
             * Kind
             * @description `local` (a file this deployment loads) or `external` (a third-party service)
             */
            kind: string;
            /** Supports */
            supports: string[];
            /** Detail */
            detail: {
                [key: string]: unknown;
            };
        };
        /** RelatedRead */
        RelatedRead: {
            /** Type */
            type: string;
            /** Value */
            value: string;
            /** Relation */
            relation: string;
        };
        /**
         * Resolution
         * @enum {string}
         */
        Resolution: "true_positive" | "benign_positive" | "false_positive";
        /** RoleAssignment */
        RoleAssignment: {
            /** Roles */
            roles: string[];
        };
        /** RoleCreate */
        RoleCreate: {
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Permissions */
            permissions?: string[];
        };
        /** RoleRead */
        RoleRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Is System */
            is_system: boolean;
            /** Permissions */
            permissions: string[];
        };
        /** RoleUpdate */
        RoleUpdate: {
            /** Description */
            description?: string | null;
            /** Permissions */
            permissions?: string[] | null;
        };
        /** RuleRead */
        RuleRead: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Type */
            type: string;
            /** Level */
            level: string;
            /** Severity Id */
            severity_id: number;
            /** Techniques */
            techniques: string[];
            /** Tactics */
            tactics: string[];
            /** Version */
            version: string;
            /** Path */
            path: string;
            /** References */
            references: string[];
            /** False Positives */
            false_positives: string[];
            /** Logsource */
            logsource?: string | null;
            threshold?: components["schemas"]["ThresholdSettings"] | null;
        };
        /** SourceCreate */
        SourceCreate: {
            /**
             * Name
             * @example web-01-auth
             */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Parser
             * @example linux_auth
             */
            parser: string;
        };
        /**
         * SourceHealth
         * @enum {string}
         */
        SourceHealth: "healthy" | "stale" | "erroring" | "awaiting_data" | "disabled";
        /** SourceRead */
        SourceRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Parser */
            parser: string;
            /** Is Enabled */
            is_enabled: boolean;
            /** Token Prefix */
            token_prefix: string;
            health: components["schemas"]["SourceHealth"];
            /** Last Event At */
            last_event_at: string | null;
            /** Events Accepted */
            events_accepted: number;
            /** Events Rejected */
            events_rejected: number;
            /** Last Error */
            last_error: string | null;
            /** Last Error At */
            last_error_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SourceUpdate */
        SourceUpdate: {
            /** Is Enabled */
            is_enabled: boolean;
        };
        /**
         * SourceWithToken
         * @description Returned only by create and rotate: the token is never retrievable afterwards.
         */
        SourceWithToken: {
            source: components["schemas"]["SourceRead"];
            /** Token */
            token: string;
        };
        /** StepCitationRead */
        StepCitationRead: {
            /**
             * Link Id
             * Format: uuid
             */
            link_id: string;
            /** Rule */
            rule: string;
            /** Title */
            title: string;
            /** Techniques */
            techniques: string[];
        };
        /** ThresholdSettings */
        ThresholdSettings: {
            /** Group By */
            group_by: string[];
            /** Count Distinct */
            count_distinct: string | null;
            /** Threshold */
            threshold: number;
            /** Window Seconds */
            window_seconds: number;
        };
        /** TimelineResponse */
        TimelineResponse: {
            /** Steps */
            steps: components["schemas"]["TimelineStepRead"][];
            /**
             * Unresolved Events
             * @description Evidence event_uids with no recorded digest, so absent from the timeline and graph
             */
            unresolved_events: string[];
        };
        /** TimelineStepRead */
        TimelineStepRead: {
            /**
             * Id
             * @description event_uid of the first event in the step
             */
            id: string;
            /**
             * First Seen
             * Format: date-time
             */
            first_seen: string;
            /**
             * Last Seen
             * Format: date-time
             */
            last_seen: string;
            /** Action */
            action: string;
            /** Outcome */
            outcome: string | null;
            /** Host */
            host: string | null;
            /** Users */
            users: string[];
            /** Process */
            process: string | null;
            /** Parent Process */
            parent_process: string | null;
            /** Command Lines */
            command_lines: string[];
            /**
             * Remote
             * @description The other side: the client of a logon, or the far end of a connection
             */
            remote: string | null;
            /** Remote Ports */
            remote_ports: number[];
            /** Domains */
            domains: string[];
            /**
             * Citations
             * @description Findings and correlation links citing these events
             */
            citations: components["schemas"]["StepCitationRead"][];
            /**
             * Events
             * @description event_uids this step stands for, in time order
             */
            events: string[];
            /** Entities */
            entities: string[];
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
            /** Expires In */
            expires_in: number;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** UserCreate */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /** Roles */
            roles?: string[];
        };
        /** UserRead */
        UserRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Org Id
             * Format: uuid
             */
            org_id: string;
            /** Email */
            email: string;
            /** Full Name */
            full_name: string;
            /** Is Active */
            is_active: boolean;
            /** Roles */
            roles: string[];
            /** Last Login At */
            last_login_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** UserUpdate */
        UserUpdate: {
            /** Full Name */
            full_name?: string | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Password */
            password?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    jwks__well_known_jwks_json_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: {
                            [key: string]: string;
                        }[];
                    };
                };
            };
        };
    };
    me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    list_users_api_v1_users_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_UserRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_user_api_v1_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_api_v1_users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deactivate_user_api_v1_users__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_api_v1_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_user_roles_api_v1_users__user_id__roles_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleAssignment"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_roles_api_v1_roles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleRead"][];
                };
            };
        };
    };
    create_role_api_v1_roles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_role_api_v1_roles__role_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_permissions_api_v1_permissions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionRead"][];
                };
            };
        };
    };
    ingest_events_api_v1_ingest_events_post: {
        parameters: {
            query?: {
                /** @description Required when using a user access token */
                source_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_parsers_api_v1_ingest_parsers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParserRead"][];
                };
            };
        };
    };
    list_sources_api_v1_ingest_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceRead"][];
                };
            };
        };
    };
    create_source_api_v1_ingest_sources_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceWithToken"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_source_api_v1_ingest_sources__source_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_source_api_v1_ingest_sources__source_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rotate_source_token_api_v1_ingest_sources__source_id__rotate_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceWithToken"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_events_api_v1_events_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_event_api_v1_events__event_uid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_findings_api_v1_findings_get: {
        parameters: {
            query?: {
                /** @description Earliest last_seen (inclusive) */
                time_from?: string | null;
                /** @description Latest last_seen (inclusive) */
                time_to?: string | null;
                severity_min?: number | null;
                rule_id?: string | null;
                technique?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingPageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_finding_api_v1_findings__finding_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                finding_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rules_api_v1_detection_rules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleRead"][];
                };
            };
        };
    };
    get_rule_api_v1_detection_rules__rule_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_incidents_api_v1_incidents_get: {
        parameters: {
            query?: {
                /** @description Earliest last_seen (inclusive) */
                time_from?: string | null;
                /** @description Latest last_seen (inclusive) */
                time_to?: string | null;
                status?: components["schemas"]["IncidentStatus"] | null;
                severity_min?: number | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentPageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_incident_api_v1_incidents__incident_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentDetailRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_incident_status_api_v1_incidents__incident_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IncidentStatusChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_timeline_api_v1_incidents__incident_id__timeline_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_graph_api_v1_incidents__incident_id__graph_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evidence_api_v1_incidents__incident_id__evidence_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_notes_api_v1_incidents__incident_id__notes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_note_api_v1_incidents__incident_id__notes_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_providers_api_v1_intel_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderRead"][];
                };
            };
        };
    };
    lookup_api_v1_intel_lookup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IntelLookup"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntelLookupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthReport"];
                };
            };
        };
    };
    config_api_v1_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformConfig"];
                };
            };
        };
    };
    list_audit_api_v1_audit_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
                action?: string | null;
                resource_type?: string | null;
                actor_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_AuditEntryRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_audit_api_v1_audit_verify_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditVerificationRead"];
                };
            };
        };
    };
}
