"""Ports the identity application layer depends on; infrastructure provides the adapters."""

from __future__ import annotations

from collections.abc import Collection, Mapping
from datetime import datetime
from typing import Protocol
from uuid import UUID

from app.core.audit.port import AuditRecorder
from app.modules.identity.domain.entities import Org, PermissionInfo, RefreshToken, Role, User


class OrgRepository(Protocol):
    async def get(self, org_id: UUID) -> Org | None: ...

    async def get_by_slug(self, slug: str) -> Org | None: ...

    async def add(self, org: Org) -> None: ...


class UserRepository(Protocol):
    async def get(self, org_id: UUID, user_id: UUID) -> User | None: ...

    async def get_by_email(self, email: str) -> User | None: ...

    async def list_page(self, org_id: UUID, *, limit: int, after_id: UUID | None) -> list[User]: ...

    async def add(self, user: User) -> None: ...

    async def update(self, user: User) -> None: ...

    async def set_roles(self, org_id: UUID, user_id: UUID, role_names: Collection[str]) -> None: ...

    async def effective_permissions(self, org_id: UUID, user_id: UUID) -> frozenset[str]: ...

    async def count_active_with_permissions(self, org_id: UUID, permissions: Collection[str]) -> int: ...

    async def count_with_all_roles(self, org_id: UUID, role_names: Collection[str]) -> int: ...


class RoleRepository(Protocol):
    async def list_for_org(self, org_id: UUID) -> list[Role]: ...

    async def get(self, org_id: UUID, role_id: UUID) -> Role | None: ...

    async def get_by_names(self, org_id: UUID, names: Collection[str]) -> list[Role]: ...

    async def add(self, role: Role) -> None: ...

    async def update(self, role: Role) -> None: ...


class PermissionRepository(Protocol):
    async def list_all(self) -> list[PermissionInfo]: ...

    async def sync_catalogue(self, catalogue: Mapping[str, str]) -> None: ...


class RefreshTokenRepository(Protocol):
    async def add(self, token: RefreshToken) -> None: ...

    async def get_by_hash(self, token_hash: str) -> RefreshToken | None: ...

    async def mark_used(self, token_id: UUID, used_at: datetime) -> bool:
        """Atomic compare-and-set; False means another request already spent the token."""
        ...

    async def revoke_family(self, family_id: UUID, revoked_at: datetime) -> int: ...

    async def revoke_all_for_user(self, user_id: UUID, revoked_at: datetime) -> int: ...


class IdentityUnitOfWork(Protocol):
    """One transaction: repository writes and their audit entries commit or roll back together."""

    @property
    def orgs(self) -> OrgRepository: ...

    @property
    def users(self) -> UserRepository: ...

    @property
    def roles(self) -> RoleRepository: ...

    @property
    def permissions(self) -> PermissionRepository: ...

    @property
    def refresh_tokens(self) -> RefreshTokenRepository: ...

    @property
    def audit(self) -> AuditRecorder: ...

    async def commit(self) -> None: ...

    async def rollback(self) -> None: ...
