"""The incident as a report an analyst can hand over: Markdown, with a citation on every claim.

What a handover has to survive is someone asking "how do you know?". So every section names the stored
events behind it (`sx.event_uid`), analyst notes are marked as statements rather than evidence, and
nothing is summarised into a sentence that the workspace cannot show the evidence for.

The report holds only what the incident already holds: the same findings, links, timeline, entities and
notes the API returns. Threat intel and AI analyses are deliberately left out — intel is another party's
claim and an analysis is the model's, and a handover document should carry the evidence, not opinions
about it.
"""

from __future__ import annotations

from collections.abc import Sequence
from datetime import datetime

from app.modules.correlation.domain.incidents import IncidentDetail, IncidentNote, LinkKind
from app.modules.correlation.domain.timeline import TimelineStep

MAX_EVENTS_PER_LINE = 8
MAX_COMMAND = 300


def _uids(events: Sequence[str]) -> str:
    shown = ", ".join(f"`{uid}`" for uid in events[:MAX_EVENTS_PER_LINE])
    extra = len(events) - MAX_EVENTS_PER_LINE
    return f"{shown} (+{extra} more)" if extra > 0 else shown or "—"


def _when(value: datetime) -> str:
    return value.astimezone(value.tzinfo).strftime("%Y-%m-%d %H:%M:%S UTC")


def render_markdown(
    detail: IncidentDetail,
    steps: Sequence[TimelineStep],
    notes: Sequence[IncidentNote],
    *,
    generated: datetime,
) -> str:
    incident = detail.incident
    findings = [link for link in detail.links if link.kind is LinkKind.FINDING]
    joins = [link for link in detail.links if link.kind is not LinkKind.FINDING]

    lines = [
        f"# {incident.title}",
        "",
        f"**{incident.severity}** · {incident.status.value} · incident `{incident.id}`",
        "",
        "| | |",
        "|---|---|",
        f"| First activity | {_when(incident.first_seen)} |",
        f"| Last activity | {_when(incident.last_seen)} |",
        f"| Findings | {incident.finding_count} |",
        f"| Events cited | {incident.event_count} |",
        f"| ATT&CK techniques | {', '.join(incident.techniques) or '—'} |",
        f"| Tactics | {', '.join(t.replace('_', ' ') for t in incident.tactics) or '—'} |",
    ]
    if incident.resolution is not None:
        lines.append(f"| Resolution | {incident.resolution.value.replace('_', ' ')} |")
    lines += [
        "",
        f"*Generated by Sentinel-X on {_when(generated)}. Every claim below cites the stored events it "
        "rests on; nothing here is inferred beyond what those events say.*",
        "",
        "## Why this severity",
        "",
    ]
    for entry in incident.assessment:
        lines.append(f"- **{entry.get('rule', 'assessment')}**: {entry.get('because', '')}")
    if not incident.assessment:
        lines.append("- No assessment was recorded.")

    lines += ["", "## What happened", ""]
    if not steps:
        lines.append("No timeline steps: the evidence events could not be read back.")
    for index, step in enumerate(steps, start=1):
        when = _when(step.first_seen)
        if step.last_seen != step.first_seen:
            when += f" to {step.last_seen.astimezone(step.last_seen.tzinfo).strftime('%H:%M:%S')}"
        outcome = f" ({step.outcome})" if step.outcome else ""
        lines.append(f"### {index}. {step.action}{outcome}")
        lines.append("")
        lines.append(f"- **When**: {when}")
        where = ", ".join(filter(None, [step.host, *step.users]))
        if where:
            lines.append(f"- **Where**: {where}")
        if step.process:
            parent = f" (started by {step.parent_process})" if step.parent_process else ""
            lines.append(f"- **Process**: {step.process}{parent}")
        for command in step.command_lines:
            lines.append(f"- **Command**: `{command[:MAX_COMMAND]}`")
        if step.remote:
            ports = f":{', '.join(str(port) for port in step.remote_ports)}" if step.remote_ports else ""
            lines.append(f"- **Remote**: {step.remote}{ports}")
        if step.domains:
            lines.append(f"- **Domains**: {', '.join(step.domains)}")
        for citation in step.citations:
            lines.append(f"- **Rule**: {citation.title or citation.rule}")
        lines.append(f"- **Evidence**: {_uids(step.events)}")
        lines.append("")

    lines += ["## Findings", "", "| Severity | Rule | Author | Events |", "|---|---|---|---|"]
    for link in findings:
        detail_map = link.detail
        severity = {1: "Info", 2: "Low", 3: "Medium", 4: "High", 5: "Critical"}.get(
            int(detail_map.get("severity_id", 0)), "Unknown"
        )
        author = str(detail_map.get("rule_author") or "—")
        source = detail_map.get("rule_source")
        if isinstance(source, str) and source:
            author = f"[{author}]({source})"
        lines.append(f"| {severity} | {detail_map.get('rule_title', '—')} | {author} | {len(link.evidence)} |")
    if not findings:
        lines.append("| — | No findings linked | — | — |")

    if joins:
        lines += ["", "## Why these belong together", ""]
        for link in joins:
            shared = ", ".join(f"`{match.key}`" for match in link.matched) or "—"
            lines.append(f"- {link.reason} · shared: {shared} · evidence: {_uids(link.evidence)}")

    lines += ["", "## Entities", "", "| Type | Value | First seen | Last seen | Events |", "|---|---|---|---|---|"]
    for entity in detail.entities:
        lines.append(
            f"| {entity.type} | `{entity.value}` | {_when(entity.first_seen)} | {_when(entity.last_seen)} "
            f"| {len(entity.events)} |"
        )
    if not detail.entities:
        lines.append("| — | none | — | — | — |")

    lines += ["", "## Analyst notes", ""]
    if notes:
        lines.append("*Statements by people, not evidence.*")
        lines.append("")
        for note in notes:
            lines.append(f"- **{_when(note.created_at)} · {note.author_email}**: {note.body}")
    else:
        lines.append("No notes were written.")

    lines += [
        "",
        "## How to check this report",
        "",
        "Every `event_uid` above is a stored event. Read one back with:",
        "",
        "```",
        "GET /api/v1/events/{event_uid}",
        "```",
        "",
        "Events are immutable, so the record behind a claim is the record that was seen when it was made.",
        "",
    ]
    return "\n".join(lines)
